export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

//LOCATION
export const CREATE_LOCATION = 'CREATE_LOCATION';
export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';

//GROUP
export const CREATE_GROUP = 'CREATE_GROUP';
export const FETCH_GROUPS = 'FETCH_GROUPS';

export const CREATE_SUBLOC = 'CREATE_SUBLOC';
export const FETCH_SUBLOCS = 'FETCH_SUBLOCS';

export const CREATE_TARGETLOC = 'CREATE_TARGETLOC';
export const FETCH_TARGETLOCS = 'FETCH_TARGETLOCS';

//CLIENT
export const CREATE_CLIENT = 'CREATE_CLIENT';
export const FETCH_CLIENT = 'FETCH_CLIENT';

//BILLRUN
export const CREATE_BILLRUN = 'CREATE_BILLRUN';
export const FETCH_BILLRUN = 'FETCH_BILLRUN';

export const FETCH_COMPUTED_FEES = 'FETCH_COMPUTED_FEES';
export const FETCH_BILLRUN_CAN = 'FETCH_BILLRUN_CAN';
export const UPDATE_BILLRUN_CAN = 'UPDATE_BILLRUN_CAN';
export const FETCH_BILLRUN_CAN_BY_ID = 'FETCH_BILLRUN_CAN_BY_ID';

//CATEGORY
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const FETCH_CATEGORY = 'FETCH_CATEGORY';

//PLAN
export const CREATE_PLAN = 'CREATE_PLAN';
export const FETCH_PLAN = 'FETCH_PLAN';
export const FETCH_PLAN_BY_CATEGORY_ID = 'FETCH_PLAN_BY_CATEGORY_ID';

//PAYMENT
export const CREATE_PAYMENT = 'CREATE_PAYMENT';
export const UPDATE_PAYMENT = 'UPDATE_PAYMENT';
export const FETCH_PAYMENT = 'FETCH_PAYMENT';
export const FETCH_PAYMENT_BY_ID = 'FETCH_PAYMENT';

//NEW
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';


//NEW NEW

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH = 'FETCH';
export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const LIKE = 'LIKE';

export const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH';
export const START_LOADING_POSTS = 'START_LOADING_POSTS';
export const END_LOADING_POSTS = 'END_LOADING_POSTS';
export const COMMENT = 'COMMENT';

//SOA
export const FETCH_SOA_BY_PMSGID = 'FETCH_SOA_BY_PMSGID';
export const FETCH_SOAS = 'FETCH_SOAS';
export const END_LOADING_SOAS =  'END_LOADING_SOAS'
export const START_LOADING_SOAS =  'START_LOADING_SOAS'
