export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

//LOCATION
export const CREATE_LOCATION = 'CREATE_LOCATION';
export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';

//GROUP
export const CREATE_GROUP = 'CREATE_GROUP';
export const FETCH_GROUPS = 'FETCH_GROUPS';

export const CREATE_SUBLOC = 'CREATE_SUBLOC';
export const FETCH_SUBLOCS = 'FETCH_SUBLOCS';

export const CREATE_TARGETLOC = 'CREATE_TARGETLOC';

//CLIENT
export const CREATE_CLIENT = 'CREATE_CLIENT';
export const FETCH_CLIENT = 'FETCH_CLIENT';

//BILLRUN
export const CREATE_BILLRUN = 'CREATE_BILLRUN';
export const FETCH_BILLRUN = 'FETCH_BILLRUN';

export const FETCH_BILLRUN_CAN = 'FETCH_BILLRUN_CAN';
export const UPDATE_BILLRUN_CAN = 'UPDATE_BILLRUN_CAN';
export const FETCH_BILLRUN_CAN_BY_ID = 'FETCH_BILLRUN_CAN_BY_ID';

//CATEGORY
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const FETCH_CATEGORY = 'FETCH_CATEGORY';

//PLAN
export const CREATE_PLAN = 'CREATE_PLAN';
export const FETCH_PLAN = 'FETCH_PLAN';
export const FETCH_PLAN_BY_CATEGORY_ID = 'FETCH_PLAN_BY_CATEGORY_ID';


